### ISSUE TITLE
Layout issues for large viewports

### ISSUE THREAD

**Issue by spond** [veg/LabSite#14]
See attached

![screen shot 2018-09-21 at 3 22 25 pm](https://user-images.githubusercontent.com/1018513/45901885-8bad0300-bdb2-11e8-9dc7-7be2b1b81e1b.png)

**Comment by rdvelazquez** [comment]
Thanks for pointing this out! 
Addressed by https://github.com/veg/LabSite/commit/298bfc59415aa3392d6b4f420036873a7caa01e0
